services:
  - type: web
    name: sumnode-api
    env: node
    plan: free
    buildCommand: |
      npm install &&
      export PUPPETEER_CACHE_DIR=/opt/render/.cache/puppeteer &&
      export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false &&
      npx puppeteer browsers install chrome &&
      node check-puppeteer.js &&
      node test-find-chrome.js &&
      node test-chrome-fix.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer